language: python
python:
  - "2.7"
# test for travis to trigger a build
# command to install dependencies
install:
  - cd ..
  - wget https://www.renpy.org/dl/6.99.12.4/renpy-6.99.12.4-sdk.tar.bz2
  - tar xf renpy-6.99.12.4-sdk.tar.bz2
  - rm renpy-6.99.12.4-sdk.tar.bz2
  - mv renpy-6.99.12.4-sdk renpy
  - cd renpy
# command to run error checks
script: ./renpy.sh "../MonikaModDev/Monika\ After\ Story/" lint 
